/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymnase;

import metier.*;

/**
 *
 * @author Corentin cadieu
 */
public class Administration extends javax.swing.JDialog {

    /**
     * Creates new form Administration
     */
    BDD req = new BDD();
    public Administration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        panelSport.setVisible(false);
        panelAccueil.setVisible(false);
        panelPratiquer.setVisible(false);
        panelAssoc.setVisible(false);
        panelA.setVisible(false);
        panelS.setVisible(false);
        panelPrat.setVisible(false);
        txtSport.setVisible(false);
        btnOkS.setVisible(false);
        btnOkA.setVisible(false);
        comboRef.setVisible(false);
        comboSport.setVisible(false);
        btnOkPrat.setVisible(false);
        cbxAssoc.setVisible(false);
        cbxSport.setVisible(false);
        panelAsso.setVisible(false);
        txtAdresse.setVisible(false);
        txtVille.setVisible(false);
        txtResp.setVisible(false);
        txtRefAsso.setVisible(false);
        btnOkAsso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPrat = new javax.swing.JButton();
        btnAssoc = new javax.swing.JButton();
        btnAccueil = new javax.swing.JButton();
        MainPanel = new javax.swing.JLayeredPane();
        panelSport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSport = new javax.swing.JTable();
        panelAccueil = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAccueil = new javax.swing.JTable();
        panelAssoc = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAssoc = new javax.swing.JTable();
        panelPratiquer = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPrat = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelAsso = new javax.swing.JPanel();
        btnAjoutAsso = new javax.swing.JButton();
        btnSupAsso = new javax.swing.JButton();
        btnOkAsso = new javax.swing.JToggleButton();
        txtAdresse = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        txtResp = new javax.swing.JTextField();
        txtRefAsso = new javax.swing.JTextField();
        btnModifierAsso = new javax.swing.JButton();
        panelPrat = new javax.swing.JPanel();
        btnAjoutP = new javax.swing.JButton();
        btnSupPrat = new javax.swing.JButton();
        cbxAssoc = new javax.swing.JComboBox<>();
        cbxSport = new javax.swing.JComboBox<>();
        btnOkPrat = new javax.swing.JButton();
        btnModifierPrat = new javax.swing.JButton();
        panelS = new javax.swing.JPanel();
        btnAjoutS = new javax.swing.JButton();
        txtSport = new javax.swing.JTextField();
        btnOkS = new javax.swing.JToggleButton();
        btnSupS = new javax.swing.JButton();
        btnModifierSport = new javax.swing.JButton();
        panelA = new javax.swing.JPanel();
        btnAjoutA = new javax.swing.JButton();
        btnSupA = new javax.swing.JButton();
        btnOkA = new javax.swing.JButton();
        comboRef = new javax.swing.JComboBox<>();
        comboSport = new javax.swing.JComboBox<>();
        btnModifierAccueil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSport.setText("Sport");
        btnSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportActionPerformed(evt);
            }
        });

        jLabel1.setText("ADMINISTRATION");

        btnPrat.setText("Pratiquer");
        btnPrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPratActionPerformed(evt);
            }
        });

        btnAssoc.setText("Association");
        btnAssoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssocActionPerformed(evt);
            }
        });

        btnAccueil.setText("Accueillir");
        btnAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccueilActionPerformed(evt);
            }
        });

        MainPanel.setPreferredSize(new java.awt.Dimension(300, 200));

        panelSport.setPreferredSize(new java.awt.Dimension(450, 150));

        tblSport.setModel(new ModelSport());
        jScrollPane1.setViewportView(tblSport);

        javax.swing.GroupLayout panelSportLayout = new javax.swing.GroupLayout(panelSport);
        panelSport.setLayout(panelSportLayout);
        panelSportLayout.setHorizontalGroup(
            panelSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(panelSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSportLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelSportLayout.setVerticalGroup(
            panelSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
            .addGroup(panelSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSportLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelAccueil.setPreferredSize(new java.awt.Dimension(450, 150));

        tblAccueil.setModel(new ModelAccueil());
        jScrollPane2.setViewportView(tblAccueil);

        javax.swing.GroupLayout panelAccueilLayout = new javax.swing.GroupLayout(panelAccueil);
        panelAccueil.setLayout(panelAccueilLayout);
        panelAccueilLayout.setHorizontalGroup(
            panelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(panelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccueilLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelAccueilLayout.setVerticalGroup(
            panelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
            .addGroup(panelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccueilLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(259, Short.MAX_VALUE)))
        );

        tblAssoc.setModel(new ModelAssoc());
        jScrollPane4.setViewportView(tblAssoc);

        javax.swing.GroupLayout panelAssocLayout = new javax.swing.GroupLayout(panelAssoc);
        panelAssoc.setLayout(panelAssocLayout);
        panelAssocLayout.setHorizontalGroup(
            panelAssocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(panelAssocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssocLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelAssocLayout.setVerticalGroup(
            panelAssocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
            .addGroup(panelAssocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssocLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tblPrat.setModel(new ModelPrat());
        jScrollPane3.setViewportView(tblPrat);

        javax.swing.GroupLayout panelPratiquerLayout = new javax.swing.GroupLayout(panelPratiquer);
        panelPratiquer.setLayout(panelPratiquerLayout);
        panelPratiquerLayout.setHorizontalGroup(
            panelPratiquerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(panelPratiquerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPratiquerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelPratiquerLayout.setVerticalGroup(
            panelPratiquerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
            .addGroup(panelPratiquerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPratiquerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        MainPanel.setLayer(panelSport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainPanel.setLayer(panelAccueil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainPanel.setLayer(panelAssoc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainPanel.setLayer(panelPratiquer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSport, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(panelAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                    .addContainerGap(9, Short.MAX_VALUE)
                    .addComponent(panelAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(panelPratiquer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(panelSport, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(panelAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPratiquer, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );

        btnAjoutAsso.setText("Ajouter");
        btnAjoutAsso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutAssoActionPerformed(evt);
            }
        });

        btnSupAsso.setText("Supprimer");
        btnSupAsso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupAssoActionPerformed(evt);
            }
        });

        btnOkAsso.setText("Ok");
        btnOkAsso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkAssoActionPerformed(evt);
            }
        });

        btnModifierAsso.setText("Modifier");
        btnModifierAsso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierAssoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAssoLayout = new javax.swing.GroupLayout(panelAsso);
        panelAsso.setLayout(panelAssoLayout);
        panelAssoLayout.setHorizontalGroup(
            panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssoLayout.createSequentialGroup()
                .addGroup(panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAssoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjoutAsso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnModifierAsso)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupAsso))
                    .addGroup(panelAssoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRefAsso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAssoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnOkAsso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelAssoLayout.setVerticalGroup(
            panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupAsso)
                    .addComponent(btnAjoutAsso)
                    .addComponent(btnModifierAsso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRefAsso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAssoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOkAsso)
                .addContainerGap())
        );

        btnAjoutP.setText("Ajouter");
        btnAjoutP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutPActionPerformed(evt);
            }
        });

        btnSupPrat.setText("Supprimer");
        btnSupPrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupPratActionPerformed(evt);
            }
        });

        btnOkPrat.setText("Ok");
        btnOkPrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkPratActionPerformed(evt);
            }
        });

        btnModifierPrat.setText("Modifier");
        btnModifierPrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierPratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPratLayout = new javax.swing.GroupLayout(panelPrat);
        panelPrat.setLayout(panelPratLayout);
        panelPratLayout.setHorizontalGroup(
            panelPratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPratLayout.createSequentialGroup()
                .addGroup(panelPratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPratLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAjoutP))
                    .addGroup(panelPratLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelPratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxAssoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifierPrat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSupPrat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOkPrat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        panelPratLayout.setVerticalGroup(
            panelPratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPratLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjoutP)
                    .addComponent(btnSupPrat)
                    .addComponent(btnModifierPrat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPratLayout.createSequentialGroup()
                        .addComponent(cbxAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPratLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOkPrat)))
                .addGap(28, 28, 28))
        );

        btnAjoutS.setText("Ajouter");
        btnAjoutS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutSActionPerformed(evt);
            }
        });

        btnOkS.setText("ok");
        btnOkS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkSActionPerformed(evt);
            }
        });

        btnSupS.setText("Supprimer");
        btnSupS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupSActionPerformed(evt);
            }
        });

        btnModifierSport.setText("Modifier");
        btnModifierSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierSportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSLayout = new javax.swing.GroupLayout(panelS);
        panelS.setLayout(panelSLayout);
        panelSLayout.setHorizontalGroup(
            panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjoutS, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSport, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSLayout.createSequentialGroup()
                        .addComponent(btnOkS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(97, Short.MAX_VALUE))
                    .addGroup(panelSLayout.createSequentialGroup()
                        .addComponent(btnModifierSport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupS)
                        .addContainerGap())))
        );
        panelSLayout.setVerticalGroup(
            panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupS)
                    .addComponent(btnAjoutS)
                    .addComponent(btnModifierSport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOkS))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnAjoutA.setText("Ajouter");
        btnAjoutA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutAActionPerformed(evt);
            }
        });

        btnSupA.setText("Supprimer");
        btnSupA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupAActionPerformed(evt);
            }
        });

        btnOkA.setText("OK");
        btnOkA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkAActionPerformed(evt);
            }
        });

        btnModifierAccueil.setText("Modifier");
        btnModifierAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierAccueilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelALayout = new javax.swing.GroupLayout(panelA);
        panelA.setLayout(panelALayout);
        panelALayout.setHorizontalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelALayout.createSequentialGroup()
                        .addComponent(comboRef, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelALayout.createSequentialGroup()
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjoutA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSport, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelALayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnOkA, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelALayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModifierAccueil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSupA)))))
                .addContainerGap())
        );
        panelALayout.setVerticalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjoutA)
                    .addComponent(btnSupA)
                    .addComponent(btnModifierAccueil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelALayout.createSequentialGroup()
                        .addComponent(comboRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelALayout.createSequentialGroup()
                        .addComponent(btnOkA)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(panelAsso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelPrat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(panelA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(panelS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(38, Short.MAX_VALUE)
                    .addComponent(panelPrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(panelAsso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAsso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccueil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAssoc, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(295, 295, 295))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAccueil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAssoc))
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportActionPerformed
        panelAccueil.setVisible(false);
        panelPratiquer.setVisible(false);
        panelAsso.setVisible(false);
        panelAssoc.setVisible(false);
        panelA.setVisible(false);
        panelPrat.setVisible(false);
        panelSport.setVisible(true);
        panelS.setVisible(true);
        req.afficheSport(tblSport);
    }//GEN-LAST:event_btnSportActionPerformed

    private void btnPratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPratActionPerformed
        panelSport.setVisible(false);
        panelAccueil.setVisible(false);
        panelAsso.setVisible(false);
        panelAssoc.setVisible(false);
        panelS.setVisible(false);
        panelA.setVisible(false);
        panelPratiquer.setVisible(true);
        panelPrat.setVisible(true);
        req.affichePrat(tblPrat, cbxAssoc, cbxSport);
    }//GEN-LAST:event_btnPratActionPerformed

    private void btnAssocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssocActionPerformed
        panelSport.setVisible(false);
        panelAccueil.setVisible(false);
        panelPratiquer.setVisible(false);
        panelPrat.setVisible(false);
        panelS.setVisible(false);
        panelA.setVisible(false);
        panelAsso.setVisible(true);
        panelAssoc.setVisible(true);
        req.afficheAssoc(tblAssoc);
    }//GEN-LAST:event_btnAssocActionPerformed

    private void btnAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccueilActionPerformed
        panelSport.setVisible(false);
        panelAsso.setVisible(false);
        panelAssoc.setVisible(false);
        panelS.setVisible(false);
        panelPrat.setVisible(false);
        panelPratiquer.setVisible(false);
        panelAccueil.setVisible(true);
        panelA.setVisible(true);
        req.afficheAccueil(tblAccueil, comboRef, comboSport);

    }//GEN-LAST:event_btnAccueilActionPerformed

    private void btnAjoutAssoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutAssoActionPerformed
        txtAdresse.setVisible(true);
        txtVille.setVisible(true);
        txtResp.setVisible(true);
        txtRefAsso.setVisible(true);
        btnOkAsso.setVisible(true);
    }//GEN-LAST:event_btnAjoutAssoActionPerformed

    private void btnSupAssoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupAssoActionPerformed
        int ligne = tblAssoc.getSelectedRow();
        req.supAssoc(tblAssoc, ligne);
    }//GEN-LAST:event_btnSupAssoActionPerformed

    private void btnOkAssoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkAssoActionPerformed
        int ligne = tblAssoc.getSelectedRow();
        String FrefAsso = (String) tblAssoc.getValueAt(ligne, 0);
        String Fresponsable = (String) tblAssoc.getValueAt(ligne, 3);
        
        String refAsso = txtRefAsso.getText();
        String adresse = txtAdresse.getText();
        String responsable = txtResp.getText();
        String ville = txtVille.getText();
        
        if(ligne != -1){
            req.modifAssoc(tblAssoc, refAsso, ville, adresse, responsable, ligne, FrefAsso, Fresponsable);
        }
        else{
            req.ajoutAssoc(tblAssoc, refAsso, ville, adresse, responsable);
        }
        
        txtAdresse.setVisible(false);
        txtVille.setVisible(false);
        txtResp.setVisible(false);
        txtRefAsso.setVisible(false);
        btnOkAsso.setVisible(false);
    }//GEN-LAST:event_btnOkAssoActionPerformed

    private void btnAjoutPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutPActionPerformed
        cbxAssoc.setVisible(true);
        cbxSport.setVisible(true);
        btnOkPrat.setVisible(true);
    }//GEN-LAST:event_btnAjoutPActionPerformed

    private void btnSupPratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupPratActionPerformed
        int ligne = tblPrat.getSelectedRow();
        req.supPrat(tblPrat, ligne);
    }//GEN-LAST:event_btnSupPratActionPerformed

    private void btnOkPratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkPratActionPerformed
        cbxAssoc.setVisible(false);
        cbxSport.setVisible(false);
        btnOkPrat.setVisible(false);
        int ligne = tblPrat.getSelectedRow();
        String refAsso = (String) cbxAssoc.getSelectedItem();
        String sport = (String) cbxSport.getSelectedItem();
        String Fsport = (String) tblPrat.getValueAt(ligne, 1);
        if(ligne != -1){
            req.modifPrat(tblPrat, sport, refAsso, Fsport, ligne);
        }
        else{
            req.ajoutPrat(tblAssoc, refAsso, sport);
        }
      
        cbxSport.setVisible(false);
        cbxAssoc.setVisible(false);
        btnOkPrat.setVisible(false);
    }//GEN-LAST:event_btnOkPratActionPerformed

    private void btnAjoutSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutSActionPerformed
        txtSport.setVisible(true);
        btnOkS.setVisible(true);
    }//GEN-LAST:event_btnAjoutSActionPerformed

    private void btnOkSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkSActionPerformed
        txtSport.setVisible(false);
        btnOkS.setVisible(false);
        int ligne = tblSport.getSelectedRow();
        String sport = txtSport.getText();
        String Fsport = (String) tblSport.getValueAt(ligne, 0);
        
        if(ligne != -1){
            req.modifSport(tblSport, sport, Fsport, ligne);
        }
        else{
            req.ajoutS(tblSport, sport);
        }
      
        txtSport.setVisible(false);
        btnOkS.setVisible(false);
    }//GEN-LAST:event_btnOkSActionPerformed

    private void btnSupSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupSActionPerformed
        int ligne = tblSport.getSelectedRow();
        req.supSport(tblSport, ligne);
    }//GEN-LAST:event_btnSupSActionPerformed

    private void btnAjoutAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutAActionPerformed
        panelS.setVisible(false);
        comboRef.setVisible(true);
        comboSport.setVisible(true);
        btnOkA.setVisible(true);
    }//GEN-LAST:event_btnAjoutAActionPerformed

    private void btnSupAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupAActionPerformed
        int ligne = tblAccueil.getSelectedRow();
        req.supAccueil(tblAccueil, ligne);
    }//GEN-LAST:event_btnSupAActionPerformed

    private void btnOkAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkAActionPerformed
        String sport = (String) comboSport.getSelectedItem();
        String salle = (String) comboRef.getSelectedItem();
        comboRef.setVisible(false);
        comboSport.setVisible(false);
        btnOkA.setVisible(false);
        int ligne = tblAccueil.getSelectedRow();
        String Fsport = (String) tblAccueil.getValueAt(ligne, 1);
        if(ligne != -1){
            req.modifAccueil(tblAccueil, salle, sport, Fsport, ligne);
        }
        else{
            req.ajoutPrat(tblAccueil, salle, sport);
        }
      
        comboRef.setVisible(false);
        comboSport.setVisible(false);
        btnOkA.setVisible(false);
    }//GEN-LAST:event_btnOkAActionPerformed

    private void btnModifierAssoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierAssoActionPerformed
        txtAdresse.setVisible(true);
        txtVille.setVisible(true);
        txtResp.setVisible(true);
        txtRefAsso.setVisible(true);
        btnOkAsso.setVisible(true);
        int ligne = tblAssoc.getSelectedRow();
        String refAsso = (String) tblAssoc.getValueAt(ligne, 0);
        String ville = (String) tblAssoc.getValueAt(ligne, 1);
        String adresse = (String) tblAssoc.getValueAt(ligne, 2);
        String responsable = (String) tblAssoc.getValueAt(ligne, 3);
        txtRefAsso.setText(refAsso);
        txtVille.setText(ville);
        txtAdresse.setText(adresse);
        txtResp.setText(responsable);
    }//GEN-LAST:event_btnModifierAssoActionPerformed

    private void btnModifierPratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierPratActionPerformed
        cbxAssoc.setVisible(true);
        cbxSport.setVisible(true);
        btnOkPrat.setVisible(true);
        cbxAssoc.disable();
        cbxAssoc.removeAllItems();
        int ligne = tblPrat.getSelectedRow();
        String refAsso = (String) tblPrat.getValueAt(ligne, 0);
        cbxAssoc.addItem(refAsso);
    }//GEN-LAST:event_btnModifierPratActionPerformed

    private void btnModifierAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierAccueilActionPerformed
        comboRef.setVisible(true);
        comboSport.setVisible(true);
        btnOkA.setVisible(true);
        comboRef.disable();
        comboRef.removeAllItems();
        int ligne = tblAccueil.getSelectedRow();
        String salle = (String) tblAccueil.getValueAt(ligne, 0);
        comboRef.addItem(salle);
    }//GEN-LAST:event_btnModifierAccueilActionPerformed

    private void btnModifierSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierSportActionPerformed
        txtSport.setVisible(true);
        btnOkS.setVisible(true);
        int ligne = tblSport.getSelectedRow();
        String sport = (String) tblSport.getValueAt(ligne, 0);
        txtSport.setText(sport);
    }//GEN-LAST:event_btnModifierSportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Administration dialog = new Administration(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane MainPanel;
    private javax.swing.JButton btnAccueil;
    private javax.swing.JButton btnAjoutA;
    private javax.swing.JButton btnAjoutAsso;
    private javax.swing.JButton btnAjoutP;
    private javax.swing.JButton btnAjoutS;
    private javax.swing.JButton btnAssoc;
    private javax.swing.JButton btnModifierAccueil;
    private javax.swing.JButton btnModifierAsso;
    private javax.swing.JButton btnModifierPrat;
    private javax.swing.JButton btnModifierSport;
    private javax.swing.JButton btnOkA;
    private javax.swing.JToggleButton btnOkAsso;
    private javax.swing.JButton btnOkPrat;
    private javax.swing.JToggleButton btnOkS;
    private javax.swing.JButton btnPrat;
    private javax.swing.JButton btnSport;
    private javax.swing.JButton btnSupA;
    private javax.swing.JButton btnSupAsso;
    private javax.swing.JButton btnSupPrat;
    private javax.swing.JButton btnSupS;
    private javax.swing.JComboBox<String> cbxAssoc;
    private javax.swing.JComboBox<String> cbxSport;
    private javax.swing.JComboBox<String> comboRef;
    private javax.swing.JComboBox<String> comboSport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelAccueil;
    private javax.swing.JPanel panelAsso;
    private javax.swing.JPanel panelAssoc;
    private javax.swing.JPanel panelPrat;
    private javax.swing.JPanel panelPratiquer;
    private javax.swing.JPanel panelS;
    private javax.swing.JPanel panelSport;
    private javax.swing.JTable tblAccueil;
    private javax.swing.JTable tblAssoc;
    private javax.swing.JTable tblPrat;
    private javax.swing.JTable tblSport;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtRefAsso;
    private javax.swing.JTextField txtResp;
    private javax.swing.JTextField txtSport;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
